load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# TODO: add HTTP archive to example after v1.0.1
# v1.0.0 doesn't work with Bazel 5
# http_archive(
#     name = "rules_gcs",
#     urls = ["https://github.com/tweag/rules_gcs/releases/download/v1.0.0/rules_gcs-v1.0.0.tar.gz"],
#     sha256 = "3a259d1e7874ab29117cf9ff8900b4d2ebe3c018c51f9b1dc4a542473eaba230",
#     strip_prefix = "rules_gcs-1.0.0",
# )

local_repository(
    name = "rules_gcs",
    path = "../..",
)

load("@rules_gcs//gcs:repo_rules.bzl", "gcs_archive", "gcs_file")

gcs_archive(
    name = "kubernetes_1_30_3",
    build_file_content = """exports_files(glob(["**"]))""",
    integrity = "sha256-9x9WRt4Xw8n3IgE9T1PlChVoInD1YXrAYdQw6moWAM0=",
    strip_prefix = "kubernetes",
    url = "gs://kubernetes-release/release/v1.30.3/kubernetes.tar.gz",
)

gcs_file(
    name = "k8s_1_30_2_release_notes",
    sha256 = "e879f76b7bac8effe4cc53bce034f258ce15b2825f3018c7078f25e832c3feb8",
    url = "gs://kubernetes-release/release/v1.30.2/release-notes.json",
)
