#!/usr/bin/env bash

set -euo pipefail
set -o errtrace

if [ "$1" != "get" ]; then
  echo "Unknown subcommand $1"
  exit 1
fi

TOKEN=$(gcloud auth application-default print-access-token || gcloud auth print-access-token)

cat << EOF
{
  "headers": {
    "Authorization": ["Bearer ${TOKEN}"]
  }
}
EOF
