name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Every day at 11:09 UTC.
    - cron: '9 11 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tidy_and_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-15, ubuntu-22.04]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_gcs
    - name: Execute Tests
      shell: bash
      run: bazelisk test //...
  integration_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-15, ubuntu-22.04]
    runs-on: ${{ matrix.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Authenticate with GCP
      id: gauth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/448697004169/locations/global/workloadIdentityPools/github-workload-pool/providers/github-provider-gcs"
        service_account: "github-service-account@ospo-data-platform.iam.gserviceaccount.com"
        export_environment_variables: true
        create_credentials_file: true
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_gcs
    - name: Execute Integration Tests
      shell: bash
      run: bazelisk test //:all_integration_tests

  all_ci_tests:
    runs-on: ubuntu-22.04
    needs: [tidy_and_test_matrix, integration_test_matrix]
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
